platform: linux
image_resource:
  type: docker-image
  source:
    repository: docker pull rest4hub/oracle-java-mvn
    tag: latest

inputs:
- name: se-labs

run:
  path: ./se-labs/attendee/concourse/tasks/unit-test.sh
